# mypy: ignore-errors
#!/usr/bin/env python3
"""Generate docs/lirix_import_topology.md — lirix-internal import edges (stdlib ast only).

Use ``python tools/gen_lirix_import_graph.py --check`` in CI to ensure the committed topology
matches a fresh generation (no hand-edits / no stale artifact).
"""

from __future__ import annotations

import argparse
import ast
import sys
from collections import defaultdict
from pathlib import Path


def _module_for_path(lirix_pkg: Path, path: Path) -> str:
    rel = path.relative_to(lirix_pkg).with_suffix("")
    parts = rel.parts
    if parts and parts[-1] == "__init__":
        parts = parts[:-1]
    return "lirix" + ("." + ".".join(parts) if parts else "")


def _import_from_absolute(*, current_mod: str, node: ast.ImportFrom) -> str | None:
    parts = current_mod.split(".")
    level = int(node.level)
    if level == 0:
        mod = node.module
        if not mod or not mod.startswith("lirix"):
            return None
        return mod
    if level > len(parts) - 1:
        return None
    base = parts[: len(parts) - level]
    abs_parts = base + node.module.split(".") if node.module else base
    if not abs_parts or abs_parts[0] != "lirix":
        return None
    return ".".join(abs_parts)


def collect_edges(lirix_pkg: Path) -> dict[str, set[str]]:
    edges: dict[str, set[str]] = defaultdict(set)
    for py in sorted(lirix_pkg.rglob("*.py")):
        if "__pycache__" in py.parts:
            continue
        current = _module_for_path(lirix_pkg, py)
        tree = ast.parse(py.read_text(encoding="utf-8"), filename=str(py))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    name = alias.name
                    if name == "lirix":
                        edges[current].add("lirix")
                    elif name.startswith("lirix."):
                        edges[current].add(name)
            elif isinstance(node, ast.ImportFrom):
                abs_mod = _import_from_absolute(current_mod=current, node=node)
                if abs_mod:
                    edges[current].add(abs_mod)
    return edges


def _top_level(mod: str) -> str:
    parts = mod.split(".")
    if len(parts) >= 2:
        return ".".join(parts[:2])
    return mod


def format_topology_markdown(edges: dict[str, set[str]]) -> str:
    lines: list[str] = [
        "---",
        "title: Lirix import topology",
        "purpose: static lirix→lirix import edges for architecture audits",
        "note: generated file; do not hand-edit (run tools/gen_lirix_import_graph.py)",
        "---",
        "",
        "# Lirix import topology",
        "",
        "Generated by `python tools/gen_lirix_import_graph.py`.",
        "",
        "## Aggregated edges (first two path segments)",
        "",
        "| From (prefix) | To (prefix) |",
        "| --- | --- |",
    ]
    agg: set[tuple[str, str]] = set()
    for src, tgts in sorted(edges.items()):
        for t in sorted(tgts):
            if src == t:
                continue
            agg.add((_top_level(src), _top_level(t)))
    for a, b in sorted(agg):
        lines.append(f"| `{a}` | `{b}` |")
    lines += [
        "",
        "## Per-module edges (lirix internal)",
        "",
        "| Source module | Imports |",
        "| --- | --- |",
    ]
    for src in sorted(edges):
        tgts = sorted(edges[src])
        if not tgts:
            lines.append(f"| `{src}` | *(none)* |")
        else:
            lines.append(f"| `{src}` | {', '.join(f'`{t}`' for t in tgts)} |")
    lines += [
        "",
        "## 中文说明",
        "",
        (
            "**中文：** 本文件为生成制品，列出 `lirix/` 包内模块之间的 import 边，"
            "供架构审计与依赖方向约束对照；**禁止手改**。更新依赖图请运行 "
            "`python tools/gen_lirix_import_graph.py`，CI 漂移校验使用 "
            "`python tools/gen_lirix_import_graph.py --check`。"
        ),
        "",
    ]
    return "\n".join(lines) + "\n"


def render_markdown(edges: dict[str, set[str]], out: Path) -> None:
    out.write_text(format_topology_markdown(edges), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/lirix_import_topology.md differs from freshly generated output.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    lirix_pkg = root / "lirix"
    if not lirix_pkg.is_dir():
        print("lirix/ package not found", file=sys.stderr)
        return 1
    edges = collect_edges(lirix_pkg)
    out = root / "docs" / "lirix_import_topology.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    fresh = format_topology_markdown(edges)
    if args.check:
        if not out.is_file():
            print(f"import-topology-check: missing {out.relative_to(root)}", file=sys.stderr)
            return 1
        existing = out.read_text(encoding="utf-8")
        if existing != fresh:
            print(
                "import-topology-check: docs/lirix_import_topology.md is stale or hand-edited.\n"
                "Regenerate with: python tools/gen_lirix_import_graph.py\n"
                "Then commit the updated markdown.",
                file=sys.stderr,
            )
            return 1
        print(f"import-topology-check: ok (matches {out.relative_to(root)})")
        return 0
    render_markdown(edges, out)
    print(f"Wrote {out.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
